-- Tracks successful payments and persistent unlock access.

CREATE TABLE IF NOT EXISTS public.user_access (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null unique,
  platform_unlocked boolean default false not null,
  low_guides_unlocked boolean default false not null,
  high_guides_unlocked boolean default false not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

CREATE TABLE IF NOT EXISTS public.payment_records (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  payment_reference text not null unique,
  payment_method text not null,
  product text not null check (product in ('platform', 'low_guides', 'high_guides')),
  amount numeric(10,2) not null,
  currency text default 'USD' not null,
  status text not null check (status in ('success', 'failed', 'pending')),
  created_at timestamp with time zone default now() not null
);

ALTER TABLE public.user_access DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_records DISABLE ROW LEVEL SECURITY;
