-- Run this script in your Supabase SQL editor to create the user_activity table
CREATE TABLE IF NOT EXISTS public.user_activity (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Note: In a production app you would want to insert a row into this table whenever 
-- a user applies for a job, unlocks a guide, updates their profile, etc.
