-- Supabase Setup Script for WorkAI Academy

-- 1. Create AI Jobs Table
CREATE TABLE IF NOT EXISTS public.ai_jobs (
  id bigint generated by default as identity primary key,
  company text not null,
  title text not null,
  type text default 'Remote',
  pay text,
  location text default 'Worldwide',
  requirements text,
  description text,
  created_at timestamp with time zone default now() not null
);

-- 2. Create Remote Jobs Table
CREATE TABLE IF NOT EXISTS public.remote_jobs (
  id bigint generated by default as identity primary key,
  company text not null,
  title text not null,
  type text default 'Remote',
  pay text,
  location text default 'Worldwide',
  category text,
  created_at timestamp with time zone default now() not null
);

-- 3. Create Guides Table
CREATE TABLE IF NOT EXISTS public.guides (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price integer default 0,
  lessons integer default 0,
  path text,
  tier text default 'low',
  created_at timestamp with time zone default now() not null
);

-- 4. Create Applications Table (Tracks which jobs a user applied for)
CREATE TABLE IF NOT EXISTS public.applications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  job_id bigint not null,
  job_type text not null check (job_type in ('ai', 'remote')),
  status text default 'In progress',
  created_at timestamp with time zone default now() not null
);

-- 5. Create User Guides Table (Tracks which guides a user has unlocked)
CREATE TABLE IF NOT EXISTS public.user_guides (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  guide_id bigint references public.guides(id) on delete cascade not null,
  created_at timestamp with time zone default now() not null
);

-- 6. Create User Stats Table
CREATE TABLE IF NOT EXISTS public.user_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null unique,
  success_rate integer default 0,
  created_at timestamp with time zone default now() not null
);

-- Turn off Row Level Security (RLS) temporarily (or implement proper policies)
-- For a quick start and since you are the admin, you can allow all access for now (or set up proper RLS later).
ALTER TABLE public.ai_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.remote_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.guides DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_guides DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_stats DISABLE ROW LEVEL SECURITY;
